services:
  backend:
    build: ./borcelle-backend
    ports:
      - "5000:5000"
    env_file:
      - ./borcelle-backend/.env

  frontend:
    build: ./borcelle-spa-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend