apiVersion: v1
kind: Service
metadata:
  name: borcelle-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: borcelle-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80